name: g6_project
services:
  frontend:
    container_name: g6-frontend
    image: g6_frontend:latest
    ports:
      - 3000:3000
    networks:
      - g6-network
    environment:
      - NGINX_PROXY=http://backend-service
volumes:
  g6-data:
networks:
  g6-network:
