import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import React, { useEffect, useState } from "react";

// export const metadata: Metadata = {
//   title: "PixelaFans",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
